INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1001, 'Comic Books');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1002, 'Movies');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1003, 'Books');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1004, 'Manga');
INSERT INTO CATEGORY  (ID, DESCRIPTION) VALUES (1005, 'Light Novel');

INSERT INTO SUPPLIER (ID, NAME) VALUES (1001, 'Panini Comics');
INSERT INTO SUPPLIER (ID, NAME) VALUES (1002, 'Amazon');
INSERT INTO SUPPLIER (ID, NAME) VALUES (1003, 'Marvel');


INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVALIABLE) VALUES (1001, 'Crises nas Infinitas Terras', 1001, 1001, 10);

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVALIABLE) VALUES (1002, 'Guerra Infinita', 1003, 1002, 5);

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVALIABLE) VALUES (1003, 'Kimetsu No Yaiba', 1002, 1004, 7);

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVALIABLE) VALUES (1004, 'Swort Art Online: Progressive', 1002, 1005, 8);

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVALIABLE) VALUES (1005, 'Pai Rico, Pai Pobre', 1002, 1003, 4);

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVALIABLE) VALUES (1006, 'Harry Potter e a Pedra filosofal', 1003, 1002, 5);
